AWStemplateFormatVersion: '2021-06-01'

Parameters:
  DynamoAtributo: 
    Type: String

Resources: 
  DynamodesdeCero:  
    Type: AWS::DynamoDB::GlobalTable
    Properties: 
      AttributeDefinitions: 
        - AttributeName: !Ref DynamoAtributo
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref DynamoAtributo
          KeyType: HASH 
      BillingMode: PAY_PER_REQUEST          
      SSESpecification: 
        SSESpecification:
           SSEEEnabled: true
      TableName: String
       

