AWStemplateFormatVersion: '2021-06-01'

# Parameters:
  # DynamoAtributo: 
    # Type: String

Resources: 
  DynamodesdeCero:  
    Type: AWS::DynamoDB::GlobalTable
    Properties: 
      AttributeDefinitions: 
        - AttributeName: DynamoAtributo # Using the attribute name directly
          AttributeType: S
      KeySchema:
        - AttributeName: DynamoAtributo # Using the attribute name directly
          KeyType: HASH 
      BillingMode: PAY_PER_REQUEST          
      SSESpecification: 
        SSESpecification:
           SSEEEnabled: true
      TableName: String
       

