AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DinamoAtributo:
    Type: String
  NombreDynamo:
    Type: String

Resources:
  DynamoDesdeCero:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !Ref DinamoAtributo
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref DinamoAtributo
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      TableName: !Ref NombreDynamo

Outputs:
  NombreDynamo:
    Value: !Ref DynamoDesdeCero
    Export:
      Name: !Sub "${AWS::StackName}-NombreDynamo"
      

